/*-----------------------------------------------------------------------------
 * AtEmRasClnt.h             file
 * Copyright                acontis technologies GmbH, Weingarten, Germany
 * Response                 Willig, Andreas
 * Description              description of file
 * Date                     2007/5/4::7:18
 *---------------------------------------------------------------------------*/

#ifndef __ATEMRASCLNT_H__
#define __ATEMRASCLNT_H__    1

/*-INCLUDES------------------------------------------------------------------*/

#include <AtEmRasType.h>
#include <AtEmRasError.h>
#include <EcOs.h>
#include "AtEmRasClntVersion.h"
#include <AtEthercat.h>
                           
/*-PACK SETTINGS-------------------------------------------------------------*/
#if defined  __GNUC__   /* GNU */

#define EC_PACKED __attribute__((aligned(4), packed))

#if (defined __RCX__)
#pragma pack (4)
#endif

#elif defined _DIAB_TOOL

#define EC_PACKED __attribute__((aligned(4), packed))

#elif defined _MSC_VER  /* MICROSOFT */

#define EC_PACKED
#pragma pack (push, 4)
#pragma warning(disable:4514)

#elif defined __MET__

#define EC_PACKED
/*#pragma pack (push, 4)*/
#pragma Push_align_members(4)

#else
#error Please check pack settings for this compiler!!!
#endif

/*-DEFINES-------------------------------------------------------------------*/

/*-TYPEDEFS------------------------------------------------------------------*/

typedef struct _ATEMRAS_T_CLNTCONDESC
{
    ATEMRAS_T_IPADDR    oAddr;              /**< [in]   Server Address */
    EC_T_WORD           wPort;              /**< [in]   Server Port */
    EC_T_DWORD          dwWatchDog;         /**< [in]   Watchdog interval when to send IDL packets */
    EC_T_DWORD          dwCycleTime;        /**< [in]   Cycle Time for Recv Polling */
    EC_T_DWORD          dwWDTOLimit;        /**< [in]   Amount of cycles without receiving commands (idles) before
                                              *         Entering state wdexpired 
                                              */
    EC_T_DWORD          dwRecvPrio;         /**< [in]   Thread Priority of RAS Receive Thread */
    EC_T_DWORD          dwPktAdminSize;     /**< [in]   Slave Packet Administrative List Size */
    EC_T_PVOID          pvConHandle;        /**< [in]   Connection Handle needed for disconnect */
} EC_PACKED ATEMRAS_T_CLNTCONDESC, *ATEMRAS_PT_CLNTCONDESC;

#define ATEMRAS_T_CLNTCONDESC_SIZE  sizeof(ATEMRAS_T_CLNTCONDESC)

typedef struct _ATEMRAS_T_CLNTPARMS
{
    EC_T_DWORD          dwKeepAliveTrigger; /**< [in]   obsolete */
    EC_T_DWORD          dwAdmPrio;          /**< [in]   Priority of Administrative task */
    EC_T_DWORD          dwAdmStackSize;     /**< [in]   Stack size of Administrative task */

    EC_T_PVOID          pvNotifCtxt;        /**< [in]   Notification context returned while calling pfNotification */
    EC_PF_NOTIFY        pfNotification;     /**< [in]   Function pointer called to notify error and status 
                                              *         information generated by Remote API Layer */
} EC_PACKED ATEMRAS_T_CLNTPARMS, *ATEMRAS_PT_CLNTPARMS;

#define ATEMRAS_T_CLNTPARMS_SIZE    sizeof(ATEMRAS_T_CLNTPARMS)

/*-PACK SETTINGS-------------------------------------------------------------*/
#if defined  __GNUC__   /* GNU */

#undef  EC_PACKED

#if (defined __RCX__)
#pragma pack ()
#endif

#elif defined _MSC_VER  /* MICROSOFT */

#undef  EC_PACKED
#pragma pack (pop)

#elif defined __MET__

#undef EC_PACKED
/*#pragma pack (pop)*/
#pragma Pop_align_members()

#else
#endif

/*-CLASS---------------------------------------------------------------------*/

/*-FUNCTION DECLARATION------------------------------------------------------*/

/*-LOCAL VARIABLES-----------------------------------------------------------*/

/*-FORWARD DECLARATIONS------------------------------------------------------*/

#ifdef __cplusplus
extern "C"
{
#endif

ATECAT_API EC_T_DWORD  emRasClntGetVersion( EC_T_VOID );
ATECAT_API EC_T_DWORD  emRasClntInit(ATEMRAS_T_CLNTPARMS oParms);
ATECAT_API EC_T_DWORD  emRasClntClose(EC_T_DWORD dwTimeout);
ATECAT_API EC_T_DWORD  emRasClntAddConnection(ATEMRAS_T_CLNTCONDESC* pConDesc, EC_T_DWORD* pdwIdMask);
ATECAT_API EC_T_DWORD  emRasClntRemoveConnection(EC_T_PVOID pvConHandle, EC_T_DWORD dwTimeout);

#if (defined INCLUDE_RAS_TRACESUPPORT)
ATECAT_API EC_T_DWORD  emRasClntTraceEnable(EC_T_BOOL bEnable);
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* __ATEMRASCLNT_H__ */

/*-END OF SOURCE FILE--------------------------------------------------------*/
