#ifndef __USER_INTERFACE_H_
#define __USER_INTERFACE_H_

#define USE_MATH_DEFINES
#include <math.h>

#include "hydra.h"
#include "hydra_types.h"
#include "robot_hydra_id.h"
#include "hydra_gains.h"

//#define RAD2DEG(x) ((x)*180.0/M_PI)
//#define DEG2RAD(x) ((x)*M_PI/180.0)

//#define MAX(a,b) ((a)>(b))?(a):(b)
//#define MIN(a,b) ((a)>(b))?(b):(a)

//#define CHK_LIM(x,l,u) MAX((l),MIN((u),(x)))

typedef struct _thread_data_t
{
    pthread_mutex_t mutex;
} thread_data_t;


void *servo_ui(void *param);


const char eef_names[][25] = {
    "rhand_x",
    "rhand_y",
    "rhand_z",
    "lhand_x",
    "lhand_y",
    "lhand_z"
};

const int eha_to_joint[EHA_MAX]=
{//ehaの番号からjointの番号を返す,直交二軸は取り敢えずjointの番号を昇順で書いとく
 JOINT_HYDRA_RHIP_YAW,
 JOINT_HYDRA_RHIP_PITCH,
 JOINT_HYDRA_RHIP_ROLL,
 JOINT_HYDRA_RKNEE_PITCH,
 JOINT_HYDRA_RKNEE_PITCH,
 JOINT_HYDRA_RKNEE_PITCH,
 JOINT_HYDRA_RANKLE_ROLL,
 JOINT_HYDRA_RANKLE_PITCH,
 JOINT_HYDRA_LHIP_YAW,
 JOINT_HYDRA_LHIP_PITCH,
 JOINT_HYDRA_LHIP_ROLL,
 JOINT_HYDRA_LKNEE_PITCH,
 JOINT_HYDRA_RKNEE_PITCH,
 JOINT_HYDRA_RKNEE_PITCH,
 JOINT_HYDRA_LANKLE_ROLL,
 JOINT_HYDRA_LANKLE_PITCH,
 JOINT_HYDRA_WAIST_PITCH,
 JOINT_HYDRA_WAIST_ROLL,
 JOINT_HYDRA_NECK_PITCH,
 JOINT_HYDRA_RSCAPLAE_YAW,
 JOINT_HYDRA_RSHOULDER_PITCH,
 JOINT_HYDRA_RSHOULDER_ROLL ,
 JOINT_HYDRA_RSHOULDER_YAW,
 JOINT_HYDRA_RELBOW_PITCH ,
 JOINT_HYDRA_RELBOW_PITCH ,
 JOINT_HYDRA_RWRIST_YAW,
 JOINT_HYDRA_RWRIST_ROLL,
 JOINT_HYDRA_RWRIST_PITCH,
 JOINT_HYDRA_LSCAPLAE_YAW,
 JOINT_HYDRA_LSHOULDER_PITCH,
 JOINT_HYDRA_LSHOULDER_ROLL,
 JOINT_HYDRA_LSHOULDER_YAW,
 JOINT_HYDRA_LELBOW_PITCH,
 JOINT_HYDRA_LELBOW_PITCH,
 JOINT_HYDRA_LWRIST_YAW,
 JOINT_HYDRA_LWRIST_ROLL,
 JOINT_HYDRA_LWRIST_PITCH,
 JOINT_HYDRA_RHAND_THB_AA,
 JOINT_HYDRA_RHAND_THB_FE,
 JOINT_HYDRA_RHAND_IDX,
 JOINT_HYDRA_RHAND_MID,
 JOINT_HYDRA_RHAND_RNG,
 JOINT_HYDRA_LHAND_THB_AA,
 JOINT_HYDRA_LHAND_THB_FE,
 JOINT_HYDRA_LHAND_IDX,
 JOINT_HYDRA_LHAND_MID,
 JOINT_HYDRA_LHAND_RNG
};







#endif
